name: CI
on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}
      - run: yarn global add now

      - run: yarn run build:modified
        working-directory: ./packages/docs
      - run: node scripts/deploy-and-alias.js ${{ github.ref }}
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}

